-- # 25 Questions on GROUP BY and HAVING

desc sh.CUSTOMERS;

-- 26. Count the number of customers in each city.

SELECT CUST_CITY, COUNT(*) AS NUM_CUSTOMERS
FROM SH.CUSTOMERS
GROUP BY CUST_CITY
ORDER BY NUM_CUSTOMERS DESC;

-- 27. Find cities with more than 100 customers.

SELECT CUST_CITY, COUNT(*) AS NUM_CUSTOMERS
FROM SH.CUSTOMERS
GROUP BY CUST_CITY
HAVING COUNT(*) > 100
ORDER BY NUM_CUSTOMERS DESC;

-- 28. Count the number of customers in each state.

SELECT CUST_STATE_PROVINCE, COUNT(*) AS NUM_CUSTOMERS
FROM SH.CUSTOMERS
GROUP BY CUST_STATE_PROVINCE
ORDER BY NUM_CUSTOMERS DESC;

-- 29. Find states with fewer than 50 customers.

SELECT CUST_STATE_PROVINCE, COUNT(*) AS NUM_CUSTOMERS
FROM SH.CUSTOMERS
GROUP BY CUST_STATE_PROVINCE
HAVING COUNT(*) < 50
ORDER BY NUM_CUSTOMERS ASC;

-- 30. Calculate the average credit limit of customers in each city.

SELECT CUST_CITY, ROUND(AVG(CUST_CREDIT_LIMIT), 2) AS AVG_CREDIT_LIMIT
FROM SH.CUSTOMERS
GROUP BY CUST_CITY
ORDER BY AVG_CREDIT_LIMIT DESC;

-- 31. Find cities with average credit limit greater than 8,000.

SELECT CUST_CITY, ROUND(AVG(CUST_CREDIT_LIMIT), 2) AS AVG_CREDIT_LIMIT
FROM SH.CUSTOMERS
GROUP BY CUST_CITY
HAVING AVG(CUST_CREDIT_LIMIT) > 8000
ORDER BY AVG_CREDIT_LIMIT DESC;

-- 32. Count customers by marital status.

SELECT CUST_MARITAL_STATUS, COUNT(*) AS NUM_CUSTOMERS
FROM SH.CUSTOMERS
GROUP BY CUST_MARITAL_STATUS
ORDER BY NUM_CUSTOMERS DESC;

-- 33. Find marital statuses with more than 200 customers.

SELECT CUST_MARITAL_STATUS, COUNT(*) AS NUM_CUSTOMERS
FROM SH.CUSTOMERS
GROUP BY CUST_MARITAL_STATUS
HAVING COUNT(*) > 200
ORDER BY NUM_CUSTOMERS DESC;

-- 34. Calculate the average year of birth grouped by gender.

SELECT CUST_GENDER, ROUND(AVG(CUST_YEAR_OF_BIRTH), 0) AS AVG_YEAR_OF_BIRTH
FROM SH.CUSTOMERS
GROUP BY CUST_GENDER;

-- 35. Find genders with average year of birth after 1990.

SELECT CUST_GENDER, ROUND(AVG(CUST_YEAR_OF_BIRTH), 0) AS AVG_YEAR_OF_BIRTH
FROM SH.CUSTOMERS
GROUP BY CUST_GENDER
HAVING AVG(CUST_YEAR_OF_BIRTH) > 1990;

-- 36. Count the number of customers in each country.

SELECT COUNTRY_ID, COUNT(*) AS NUM_CUSTOMERS
FROM SH.CUSTOMERS
GROUP BY COUNTRY_ID
ORDER BY NUM_CUSTOMERS DESC;

-- 37. Find countries with more than 1,000 customers.

SELECT COUNTRY_ID, COUNT(*) AS NUM_CUSTOMERS
FROM SH.CUSTOMERS
GROUP BY COUNTRY_ID
HAVING COUNT(*) > 1000
ORDER BY NUM_CUSTOMERS DESC;

-- 38. Calculate the total credit limit per state.

SELECT CUST_STATE_PROVINCE, SUM(CUST_CREDIT_LIMIT) AS TOTAL_CREDIT_LIMIT
FROM SH.CUSTOMERS
GROUP BY CUST_STATE_PROVINCE
ORDER BY TOTAL_CREDIT_LIMIT DESC;

-- 39. Find states where the total credit limit exceeds 100,000.

SELECT CUST_STATE_PROVINCE, SUM(CUST_CREDIT_LIMIT) AS TOTAL_CREDIT_LIMIT
FROM SH.CUSTOMERS
GROUP BY CUST_STATE_PROVINCE
HAVING SUM(CUST_CREDIT_LIMIT) > 100000
ORDER BY TOTAL_CREDIT_LIMIT DESC;

-- 40. Find the maximum credit limit for each income level.

SELECT CUST_INCOME_LEVEL, MAX(CUST_CREDIT_LIMIT) AS MAX_CREDIT_LIMIT
FROM SH.CUSTOMERS
GROUP BY CUST_INCOME_LEVEL
ORDER BY MAX_CREDIT_LIMIT DESC;

-- 41. Find income levels where the maximum credit limit is greater than 15,000.

SELECT CUST_INCOME_LEVEL, MAX(CUST_CREDIT_LIMIT) AS MAX_CREDIT_LIMIT
FROM SH.CUSTOMERS
GROUP BY CUST_INCOME_LEVEL
HAVING MAX(CUST_CREDIT_LIMIT) > 15000
ORDER BY MAX_CREDIT_LIMIT DESC;

-- 42. Count customers by year of birth.

SELECT CUST_YEAR_OF_BIRTH, COUNT(*) AS NUM_CUSTOMERS
FROM SH.CUSTOMERS
GROUP BY CUST_YEAR_OF_BIRTH
ORDER BY CUST_YEAR_OF_BIRTH;

-- 43. Find years of birth with more than 50 customers.

SELECT CUST_YEAR_OF_BIRTH, COUNT(*) AS NUM_CUSTOMERS
FROM SH.CUSTOMERS
GROUP BY CUST_YEAR_OF_BIRTH
HAVING COUNT(*) > 50
ORDER BY NUM_CUSTOMERS DESC;

-- 44. Calculate the average credit limit per marital status.

SELECT CUST_MARITAL_STATUS, ROUND(AVG(CUST_CREDIT_LIMIT), 2) AS AVG_CREDIT_LIMIT
FROM SH.CUSTOMERS
GROUP BY CUST_MARITAL_STATUS
ORDER BY AVG_CREDIT_LIMIT DESC;

-- 45. Find marital statuses with average credit limit less than 5,000.

SELECT CUST_MARITAL_STATUS, ROUND(AVG(CUST_CREDIT_LIMIT), 2) AS AVG_CREDIT_LIMIT
FROM SH.CUSTOMERS
GROUP BY CUST_MARITAL_STATUS
HAVING AVG(CUST_CREDIT_LIMIT) < 5000
ORDER BY AVG_CREDIT_LIMIT ASC;

-- 46. Count the number of customers by email domain (e.g., `company.example.com`).

SELECT SUBSTR(CUST_EMAIL, INSTR(CUST_EMAIL, '@') + 1) AS EMAIL_DOMAIN, COUNT(*) AS NUM_CUSTOMERS
FROM SH.CUSTOMERS
GROUP BY SUBSTR(CUST_EMAIL, INSTR(CUST_EMAIL, '@') + 1)
ORDER BY NUM_CUSTOMERS DESC;

-- 47. Find email domains with more than 300 customers.

SELECT SUBSTR(CUST_EMAIL, INSTR(CUST_EMAIL, '@') + 1) AS EMAIL_DOMAIN, COUNT(*) AS NUM_CUSTOMERS
FROM SH.CUSTOMERS
GROUP BY SUBSTR(CUST_EMAIL, INSTR(CUST_EMAIL, '@') + 1)
HAVING COUNT(*) > 300
ORDER BY NUM_CUSTOMERS DESC;

-- 48. Calculate the average credit limit by validity (`CUST_VALID`).

SELECT CUST_VALID, ROUND(AVG(CUST_CREDIT_LIMIT), 2) AS AVG_CREDIT_LIMIT
FROM SH.CUSTOMERS
GROUP BY CUST_VALID
ORDER BY AVG_CREDIT_LIMIT DESC;

-- 49. Find validity groups where the average credit limit is greater than 7,000.

SELECT CUST_VALID, ROUND(AVG(CUST_CREDIT_LIMIT), 2) AS AVG_CREDIT_LIMIT
FROM SH.CUSTOMERS
GROUP BY CUST_VALID
HAVING AVG(CUST_CREDIT_LIMIT) > 7000
ORDER BY AVG_CREDIT_LIMIT DESC;

-- 50. Count the number of customers per state and city combination where there are more than 50 customers.

SELECT CUST_STATE_PROVINCE, CUST_CITY, COUNT(*) AS NUM_CUSTOMERS
FROM SH.CUSTOMERS
GROUP BY CUST_STATE_PROVINCE, CUST_CITY
HAVING COUNT(*) > 50
ORDER BY NUM_CUSTOMERS DESC;